== Selección de la Vida de Elizabeth Stirredge

Le ha placido al Señor considerarme digna de viajar en el camino a Sión,
un camino que he encontrado recto y estrecho.
¡Oh, muchos que han sido llamados y algunos que han entrado en él,
se han ido por senderos y caminos torcidos de nuevo,
pero yo he descubierto el bendito efecto de mantenerse en el camino correcto!
Por tanto, tengo sobre mi espíritu una gran preocupación por mis hijos,
que vienen después de mí, que no se olviden de mantenerse en el camino correcto,
después de que al Señor le haya placido quitarme de entre ellos.
Está en mi corazón, en la medida que mi Padre celestial quiera ayudarme,
dejar un corto testimonio detrás de mí para mis hijos,
sobre algunos acontecimientos de mi vida y de la bondad del Señor para conmigo,
a lo largo de toda mi vida, es decir, hasta el día de hoy.
En efecto, Él es digno de ser por siempre recordado,
y tendrá la alabanza de Su propia obra para siempre.

Nací en 1634 en Thornbury, Gloucestershire, de padres honestos,
temerosos de Dios y con un gran celo durante sus vidas.
El nombre de mi padre era William Tayler, y siendo uno de los llamados Puritanos,
profetizó de los Amigos muchos años antes de que vinieran.
Él dijo: "`Viene un día en el que la verdad real se manifestará gloriosamente,
más gloriosamente que nunca desde los días de los apóstoles, pero no viviré para verlo.`"
Él murió en la fe de esto, siete años antes de que vinieran los Amigos.
A menudo recuerdo su vida honesta y casta,
ni olvido sus oraciones fervientes y celosas entre su familia.

Mis padres me criaron de una manera muy estricta,
por lo que era una extraña para el mundo y sus caminos.
En mis tiernos años era de un corazón triste, y por un temor interno,
estaba muy preocupada sobre lo que sería de mí cuando muriera.
Cada vez que me encontraba cerca de alguien que hablaba groseramente, o juraba,
o estaba dominado por la bebida, me daba pavor pasar por ahí. ¡Oh,
el pánico y terror que caían sobre mí cuando oía un trueno!
Entonces buscaba el lugar más privado que podía para llorar en secreto,
pensando que el Señor tomaría venganza sobre las cabezas de los
impíos. Cuando veía los destellos de los relámpagos pensaba:
"`¡Oh, adónde iré para esconderme de la ira del pavoroso y terrible Dios!`"
En consecuencia, era poseída por una preocupación por mi alma,
y antes de los diez años estaba tan llena de temores y dudas,
que no podía deleitarme con nada de este mundo.

Cuando alcancé años de mayor madurez,
iba a escuchar a los que eran considerados los mejores hombres,
quienes vivían de acuerdo con lo que se les había dado a conocer.
Me deleitaba oírlos y estar en compañía de los que hablaban de cosas buenas,
y conversaban de las Escrituras, de Dios y de Cristo, y de la gloria del cielo.
¡Oh, cuán delicioso era para mí! Pero aún no estaba satisfecha,
porque descubrí que no era un testigo vivo de los estados y condiciones
que el pueblo de Dios había tenido en los días de antaño;
y que yo no sabía cómo lograr eso.
Entonces lloraba y decía en mi corazón:
"`¡Ojalá hubiera nacido en los días cuando el Señor
le hablaba a Moisés y a los hijos de Israel,
y cuando con un grande y maravilloso poder sacó a Su pueblo de Egipto,
a través del Mar Rojo.
Entonces sabría cómo caminar en el camino correcto,
cómo hacer lo que el Señor requiere de mí y cómo
tener conocimiento y estar familiarizada con mi Hacedor.
Entonces sabría cuándo complazco al Señor o no, a quien mi alma ama;
pero ahora no sé cómo conocerlo a Él!`"

¿De qué no me habría apartado con tal de haber disfrutado del Señor y
de haber tenido la seguridad de la salvación? No tengo la menor duda,
de que si hubiera sido posible para mí haber disfrutado de todo el mundo,
voluntariamente me habría separado de él,
por la paz y satisfacción de mi pobre y angustiada alma que lloraba sin esperanza.
Muchas veces y muchas horas pasaba sola, leyendo y llorando cuando ningún ojo me veía,
ni ningún oído me oía; sin embargo, no encontraba consuelo en la lectura,
pues la Biblia era un libro sellado para mí. Entonces lloraba y decía: "`¡Oh,
si hubiera nacido en los días cuando nuestro bendito
Salvador Jesucristo estaba sobre la tierra.
Cómo lo habría seguido y me habría sentado a Sus pies,
tal como lo hizo María. Cuán voluntariamente habría
dejado la casa de mi padre y todas mis relaciones,
por la verdadera paz y seguridad de vida eterna para mi alma inmortal!`"

Estaba muy entristecida bajo este ejercicio,
tanto que mi madre comprendió que me estaba consumiendo y temía mucho mi muerte.
Entonces me decía: "`¿Acaso no puedes tener deleite en nada?
¿Por qué no caminas por los campos con los jóvenes para divertirte y deleitarte en algo?`"
Así que para complacerla, algunas veces salía con jóvenes sobrios,
cuando habíamos terminado nuestro trabajo, pero no encontraba consuelo en ello.
Entonces caí en la costumbre de leer las Escrituras sólo en privado, leyendo y llorando,
debido a que veía que el poder y el Espíritu celestiales no tenían dominio en mí,
como lo tenían en aquellos que dieron las Escrituras,
y sabía que nada más sino la Sustancia me daría verdadera satisfacción.

Entonces caía sobre mis rodillas para orar al Señor,
con mi corazón lleno de tristeza y lágrimas rodando por mi rostro,
pero sin poder pronunciar una palabra.
Esto me parecía muy extraño,
y me hacía pensar que no había nadie como yo en todo el mundo.
Esto era obra del enemigo, que quería persuadirme de que no había nadie como yo,
y que debido a que no podía orar con palabras (como otros sí podían),
y a que estaba bajo estas aflicciones,
el Señor no tenía cuidado de mí. Pero el enemigo es un mentiroso,
porque el Señor estaba cerca de mí en cada prueba,
quebrantando mi corazón y derritiendo mi espíritu, o de lo contrario,
no me habría sucedido así. ¡Sí, mi alma ahora puede ver Su bondad, pues Él estaba cerca,
aunque yo no estaba consciente de eso y pensaba que nadie era tan miserable como yo!

El enemigo se esforzó por derribarme y hacerme caer en desesperación,
y fue la gran misericordia del Señor lo que verdaderamente me preservó de ello,
pues mi tristeza era grande y mi angustia mucha.
La serpiente me seguía con sus tentaciones, y yo carecía del entendimiento correcto,
sobre el lugar donde debía encontrar mi fortaleza.
Debí haberme quedado quieta y esperar en el Dios vivo la fuerza para vencerlo,
pero en lugar de hacerlo,
el enemigo me molestaba y me seguía con sus sutiles atracciones;
en algunas ocasiones para arrastrar mi mente a las vanidades de este mundo,
y para que me deleitara vistiéndome con ropas finas
para parecer hermosa a los ojos del mundo.
"`Porque,`" decía el enemigo,
"`esa tristeza y angustia bajo las que estás no resultarán de beneficio o consuelo,
ni serás de ninguna estima entre los que están cerca; por tanto, deléitate y descansa.`"
¡Él es un mentiroso y lo ha sido desde el principio!
No mis queridos hijos,
no le crean cuando se encuentren bajo alguna de sus tentaciones o pruebas,
ni cuando sean conducidos por el Señor por la prueba de su fe y paciencia,
cualquiera que sea la manera que a Él le plazca hacerlo.
El enemigo traicionará a tantos como pueda, por lo tanto,
miren al Señor y manténgalo en sus memorias, oren a Él en sus mentes,
aunque no puedan pronunciar una palabra.
Tengan la seguridad de que Él
está cerca para ayudar a Sus afligidos hijos en todo momento.

Ojalá yo hubiera sabido esto en los días de mi ignorancia, en mi juventud y tiernos años,
cuando el Señor estaba trabajando en mi corazón y yo no lo sabía. Por falta de entendimiento,
el enemigo me traicionó y me desvió. Lo escuché a
él y a los jóvenes que estaban cerca de mí,
y me convencieron de que el mundo tenía mucho que sería
de gran beneficio para mí. Tras la muerte de mi padre,
apenas me quedaba un amigo,
y en mi angustia y aflicción estaba dispuesta a buscar un poco de descanso y consuelo.
Entonces le presté oído al enemigo de mi alma y dejé que mi mente fuera tras la ropa fina.
Y cuando mi mente fue apartada, descubrí que no conocía límites,
porque incluso cuando me vestía tan finamente como podía, apenas me daba contentamiento.
Y cuando tenía algo nuevo, y luego veía otra cosa, o una tercera,
estaba tan deseosa de ella, como lo había estado de la primera, y por tanto,
siempre estaba insatisfecha.
El enemigo mentiroso me había prometido descanso y paz, pero no pudo dármelo.
Es un mentiroso y siempre lo ha sido,
y mi alma está en enemistad contra él. ¡Qué el Señor me guarde a mí y a mi casa,
de sus trampas para siempre!

Sin embargo, a pesar de que él había arrastrado mi mente,
el Señor no me dejó. A menudo sentía preocupación
por mi condición y por lo que sería de mí,
y si en algún momento me sentía atraída por la ligereza o la risa,
sentía que algo golpeaba mi corazón y traía gran pesadez sobre mi espíritu.
Tan pronto como el enemigo tiraba
de mi mente hacia el orgullo y a deleitarme en la ropa fina,
descubría que estas cosas se convertían en una carga.
Yo no sabía qué era lo que me reprendía y nunca imaginé
que era el Señor (quien es siempre bueno y clemente,
amable, misericordioso y lento para la ira,
y no desea que las personas corran hacia la destrucción).
Nunca pensé que el Señor mirara tan de cerca mis caminos,
pero desde entonces le ha placido abrir mis ojos
y puedo ver para atrás y admirar Su bondad.
¡Bendito sea Su digno nombre y el brazo derecho de Su fuerza,
porque pronto se convirtió en mi Guía y evitó, en gran medida,
que me topara con las maldades del mundo que tan comunes son en los jóvenes.
Sí, Él me tomó de la mano y me guió, incluso en mis tiernos años cuando yo no lo sabía!

Poco tiempo después de esto, en 1654,
al Señor (en las riquezas de Su amor) le plació preparar
y enviar a dos fieles siervos y obreros Suyos,
la obra de los cuales Él había prosperado grandemente; dos hombres de digna memoria,
los estimados John Audland y John Camm.
Cuando escuché el relato de ellos,
un temor vino sobre mi corazón. Al oír de su sencillez, comencé a pensar:
"`¿Cómo me humillaré para ir a escucharlos?`"
Pero un corto tiempo después fijaron una reunión, donde me tocaba estar.
Cuando entré a la reunión, el querido John Audland estaba predicando.
Tan pronto como oí su voz, esta me atravesó,
y cuando oí su testimonio y contemplé su sólido semblante, ¡oh,
cómo se turbó mi corazón dentro de mí! Yo no sabía que sería de mí.

Después que terminó la reunión,
me separé de los que me acompañaban y caminé sola dos millas,
para que ningún oído pudiera escucharme presentarle
mi queja al Señor. En amargura de espíritu clamé:
"`Señor, ¿qué debo hacer para ser salva?
Haré cualquier cosa por la seguridad de la vida eterna.
Si Te place aceptarme bajo cualquier condición,
no me importará lo que vaya a ser de este cuerpo;
incluso si debo encontrar una cueva en la cual llorar el resto de mis días en tristeza
y no vuelva a ver a nadie más.`" Pero le agradó al Señor abrir los ojos de mi entendimiento
y llevarme por un camino que no conocía. Él comenzó la obra del primer día en mi corazón,
que era:
"`El Espíritu de Dios se movía sobre la faz de las
aguas...y apartó Dios la luz de las tinieblas.`"
Y cuando esta separación fue hecha, pude ver mi camino en la luz,
la que era la '`luz en los pies de David y la lámpara en sus caminos`';
la luz que ordenará los caminos de todos correctamente, si le prestan atención.

Sería demasiado tedioso pasar por cada estado en particular,
pero mis más fervientes clamores eran que el Señor me guiara por el camino correcto,
creara en mí un corazón nuevo y renovara un espíritu recto dentro de mí. Yo decía:
"`Sea lo que yo sea, que lo sea ante Tus ojos y no ante los hombres.
No me preocupa este cuerpo externo,
pero redime mi alma de la muerte y sácala de este horrible
hoyo donde estoy retenida como con cadenas de oscuridad.
Pues si Tú, en infinita misericordia,
no inclinas Tu oído hacia mi clamor y no tienes compasión de mí, pereceré para siempre,
porque no puedo hacer nada más.`" Puedo verdaderamente decir,
que mi corazón estaba lleno de pena y suspiraba antes de comer,
y mis lágrimas eran mi triste comida.
Cuando me acostaba estaba triste y mojaba la almohada
con mis lágrimas antes de poder descansar,
y cuando me levantaba estaba sobre mi corazón el temor del Señor.

¡Oh, mi alma no puede menos que magnificar al Dios vivo, quien es digno de alabanza,
honor, renombre,
acción de gracias y obediencia para siempre! ¿Por
qué? Porque se ha dignado bajar al estado de Su sierva,
inclinado Su oído a mis oraciones y considerado mis clamores.
Sí, Él ha respondido mi petición,
y ha concedido el deseo de mi corazón de ser guiada en el camino correcto.
Los pobre viajeros a Sión saben muy bien que este es el comienzo, o un paso en el camino,
y puedo decir en verdad,
que nunca codicié la gloria del cielo más de lo que
deseaba caminar en el camino que conduce a ella.
Entonces realmente creí que el Señor quiere redimir a un pueblo del mundo,
de su manera de hablar, de su modo de casarse y enterrar a los muertos,
y de toda la hipocresía del mundo.
En realidad, yo buscaba este cambio antes de que viera alguna aparición de este.
Pero mi temor era que yo no viviría para verlo,
porque el enemigo siempre me seguía con sus tentaciones,
para llevarme a la incredulidad y hacerme caer en la desesperación. ¡Oh,
mi alma no puede sino darle gloria, honor y renombre al Señor Dios,
porque Él es digno de recibirlo por los siglos de los siglos!

Y ahora hijos míos, esto es para que lo recuerden y lo mantengan cerca de ustedes,
para que puedan conocer siempre el camino a la gloria del cielo,
y disfrutar verdadera paz y satisfacción. ¡Oh, este es un camino recto y estrecho,
y el que piense que no lo es, está equivocado!
Aférrense a la cruz todos los días de sus vidas, y al lenguaje de la verdad,
y más especialmente: '`Guarden sus corazones con toda diligencia,
porque de él mana la vida.`' Entonces serán acercados al Señor y lo conocerán
más y más. Esto es por lo que mi alma lloraba en mis tiernos años,
llanto que no puedo olvidar y espero nunca hacerlo,
porque encuentro los buenos efectos de él día tras día. En realidad,
esto inclina mi espíritu y humilla mi corazón,
manteniendo en mí un recuerdo vivo de lo que el Señor ha hecho por mí;
aunque le plació a Él darme una copa amarga para beber y alimentarme con el pan de aflicción,
y permitir que se me acercara una tentación tras otra.

Porque el enemigo, la serpiente astuta, el dragón antiguo,
que era más astuto que todos los animales del campo,
me seguía con sus mentiras para persuadirme de que el Señor no se interesaba por mí;
porque si lo hubiera hecho,
no me habría afligido así. "`No hay nadie como tú,`" decía el maligno,
"`mira hacia afuera y ve si puedes encontrar a alguien cuyas penas sean como las tuyas.`"
Entonces, salía a caminar a lugares ocultos, donde ningún ojo me pudiera ver,
ni oído oír, para clamar al Señor,
quien dulcemente ha consolado y refrescado mi espíritu muchas veces,
y ha mantenido mi cabeza por encima de las aguas.
Bendito sea el digno nombre del Señor mi Dios y el brazo derecho de Su fuerza,
que ha forjado maravillosamente mi liberación. Y maldito sea el dragón antiguo,
quien siempre ha envidiado la prosperidad del hombre.
Pues él se esforzaba por destruir la bendita obra del Señor (tanto como le era posible),
incluso después de que el Señor había hecho mucho por mí,
y había redimido mi alma de la muerte en buena medida,
por medio de una mano poderosa y un brazo extendido.
Sí, incluso después,
de haberme sacado de las tinieblas de Egipto y llevado a través del Mar Rojo,
donde mi alma tenía verdadera razón para cantar alabanzas
al altísimo Dios que vive para siempre.
¡Oh, qué nunca olvide esta grande y maravillosa liberación, y en su lugar,
me mantenga en lo que inclina mi corazón día a día
y humilla mi espíritu delante del Señor!
A Él le ha agradado hacer más por mí de lo que mi lengua es capaz de declarar,
aunque puedo decir,
que mis ojos han visto aflicciones y que "`ninguna
disciplina al presente parece ser causa de gozo,
sino de tristeza; pero después da fruto apacible de justicia.`"

Ahora, mis queridos hijos,
mi objetivo es familiarizarlos un poco con la obra del Señor en mi corazón,
y con las artimañas y tretas sutiles del enemigo de sus almas inmortales.
Su método es poner sus cebos según la naturaleza del individuo,
porque allí es más probable que predomine,
y como yo tenía un corazón triste y sujeto a ser abatido,
se esforzaba con todas sus fuerzas por hacerme caer en desesperación e incredulidad,
tratando de persuadirme de que yo no soportaría hasta el final.
Entonces yo oraba al Señor pidiéndole que me guardara hasta el final,
porque mi aflicción era muy grande, tanto interna como externamente.
Pero el enemigo arrojaba muchas cosas delante de mí,
las cuales me parecían muy difíciles de atravesar, y cuando mi mente estaba afligida,
él ganaba terreno en mí y me llenaba de imaginaciones, hasta que sin darme cuenta,
mi corazón se endurecía y perdía el dulce disfrute
y la comunión celestial con aquello que me consolaba.
Y cuando el enemigo había obtenido un poco de terreno,
ponía cebos tan compatibles con mi naturaleza,
que cuando recordaba la condición en la que estaba
antes (y que por un corto tiempo había perdido),
tenía una gran causa para llorar delante del Señor, quien era capaz de liberarme,
como lo había hecho muchas veces.

Sin embargo, el enemigo prevaleció sobre mí un poco más,
incluso mientras presentaba mi queja delante del Señor, diciendo en mi corazón:
"`No hay tristeza como la mía`";
pues yo había perdido a mi Amado y mi pérdida era grande.
Este lamento era muy acorde con mi condición,
pero la astuta serpiente me persuadió de que yo estaba descontenta,
que era murmuradora y quejumbrosa, y que había cansado al Señor con mi clamor.
Entonces creí que debía ser excluida de Su reino,
porque yo sabía que los murmuradores y quejumbrosos
habían sido los que habían perecido en el desierto.
Así fui atrapada por su sutileza y convencida de que era en vano seguir esforzándome,
pues nunca heredaría el reino de los cielos.
Pero él era un mentiroso y siempre lo será,
y mi alma está en enemistad contra él. ¡Qué el Señor en quien confío,
me preserve a mí y a mi casa para siempre!

Tenía veintiún años cuando estaba en esta condición. Pero
le agradó a mi Padre celestial (quien tenía cuidado de mí),
darme una ruta de escape de esta trampa,
porque poco tiempo después asistí a una reunión en
la que estaba el siervo fiel del Señor,
William Dewsbury.
Este hombre fue un mensajero del Señor para muchos,
y ese día su testimonio fue mayormente para los angustiados y afligidos,
los sacudidos por la tempestad y sin consuelo;
estado en el cual se encontraban muchos en aquel momento, en 1655.
Después que finalizó la reunión, me dio temor ir donde él,
porque pensaba que tenía un gran discernimiento y
sería consciente de la dureza de mi corazón,
y si me juzgaba, no podría soportarlo.
Sin embargo,
descubrí que no podía irme en paz hasta que hablara con él. Al ver que me acercaba mucho,
levantó su mano y en alta voz me dijo: "`Querido cordero,
juzga todos los pensamientos y cree, porque bienaventurados los que creen y no ven.`"
Y luego, nuevamente dijo en voz alta: "`Los que vieron y creyeron fueron bendecidos,
pero más bendecidos son los que creen y no ven.`"
¡Oh, él tenía buenas nuevas para mí, y en ese momento su testimonio fue de gran poder,
porque la dureza fue quitada y mi corazón fue abierto por el antiguo
poder que abrió el corazón de Lidia (Hechos 16:14). ¡Alabanzas
eternas sean dadas Al que está sentado en el trono para siempre,
quien me ha preservado fuera de las trampas y de las astutas artimañas del adversario!

Mi alma no puede sino bendecir y alabar al Señor mi Dios,
quien me ha preservado del mal del mundo.
Mis queridos hijos, ustedes han sido criados en el camino de la verdad,
y esta les ha sido dada a conocer, por tanto,
confíen en Su nombre y crean que Él los guardará hasta el fin; lo cual ciertamente hará,
si no se apartan de Él. Mis oraciones son de día y de noche por ustedes.
Recuerden los muchos peligros de los que han sido preservados,
los cuales bien pudieron haber sido un peligro para sus vidas.
Pero el Señor, en Su infinita bondad, los ha guardado a todos hasta este momento,
para que puedan servirle.

Por lo tanto, hijos míos, no olviden su deber para con el Señor,
ni del consejo que Jesucristo les dio a Sus discípulos,
de velar y orar para que fueran preservados de todos los peligros,
tanto internos como externos.
Ustedes pueden caer fácilmente en esto, si no se mantienen cerca del Guía de su juventud;
pero si se mantienen asidos a Él, Él nunca se apartará de ustedes.
Y si ustedes "`se acuerdan de su Creador en los días de su juventud,`" Él ciertamente
los guardará en la hora de la tentación y tendrá cuidado de ustedes.
Si ustedes '`buscan primeramente el reino de Dios y su justicia,
todas las demás cosas les serán añadidas.`' Él ha dicho que no puede mentir, por tanto,
pongan su confianza en Él para siempre.
Entonces mi Padre celestial hará por ustedes como hizo conmigo en los
días de mis tiernos años. Porque Él me tomó de la mano y me condujo por
un camino que no conocía. Él cambió las tinieblas en luz delante de mí,
y me ha preservado hasta este mismo día en pacto con Él. "`Alabanzas y
honor eternos sean dados a Su santo nombre para siempre,`" dice mi alma.

Tal vez recuerden las muchas estrecheces y dificultades
que el Señor me ha permitido atravesar,
aunque débil y grandemente afectada por enfermedades,
y muy cerca de la tumba muchas veces.
Pero el Señor renovaba mi fuerza una y otra vez para que
diera un testimonio fiel de Él y de Su bendita verdad.
El Señor, mi Redentor, me ha llevado a través de muchas dificultades,
y cuando miro hacia atrás y considero cómo ha escapado mi alma hasta este día,
me lleno de admiración. Sin embargo,
a menudo viene delante de mí lo que dijo Cristo Jesús:
"`Mayor es el que está en vosotros, que el que está en el mundo.`"
Y lo que el Señor les dijo a Sus discípulos: "`Pero confiad, yo he vencido al mundo.`"
En verdad, esto ha sido de consuelo para mí muchas veces.

Con frecuencia recuerdo lo que un siervo y ministro fiel de Jesucristo,
cuyo nombre era Miles Halhead, me dijo cuando yo estaba bajo gran prueba.
Él me miró fijamente y dijo: "`Querida hija, si continúas en la verdad,
serás una honorable mujer para el Señor,
y el Señor Dios te honrará con Su bendito testimonio.`"
Diez años después de esto, en 1665, él regresó al lugar donde yo vivía y me dijo:
"`Mi amor y vida están contigo, por el bien de la bendita obra que continúa en ti.
Que el Señor te mantenga fiel,
ya que Él requerirá cosas más difíciles de ti de las que eres consciente.
Qué Él te dé fuerza para cumplir Su voluntad y te mantenga fiel para Su bendito testimonio.
Mis oraciones serán para ti tan a menudo como te recuerde.`"
Poco tiempo después de esto,
el Señor abrió mi boca con un testimonio y una gran prueba cayó sobre nosotros,
porque fuimos expuestos a mucho sufrimiento, pues perdimos los bienes,
recibimos golpizas, fuimos lanzados de un lado a otro,
arrastrados de nuestros lugares de reunión y muchos otros abusos.
Debido a nuestros perseguidores,
nuestras vidas corrían gran peligro cuando íbamos a nuestras reuniones.
Los informadores eran tan malvados e inhumanos, y estaban tan llenos de envidia y locura,
que blasfemaron diciendo que "`no era más pecado matarnos que matar
un piojo,`" y "`que bañarían sus espadas en nuestra sangre.`"
Y todas estas cosas fueron la menor de nuestras penas,
porque en este tiempo de gran sufrimiento,
un espíritu de egoísmo y separación empezó a surgir también entre los Amigos.
Sin embargo, pude verdaderamente decir: "`Mi corazón está rendido para servir al Señor,
pase lo que pase.`"
Y bendito sea el Señor nuestro Dios, quien vive para siempre,
porque en ninguna forma fuimos atemorizados por esas cosas, ni preocupados por ellas,
porque sabíamos que Aquel en quien creíamos era capaz de librar a los
escogidos que habían puesto su confianza en Él. Mis queridos hijos,
algunas de estas cosas ustedes las conocen, sus ojos las han visto,
y aunque eran muy jóvenes y tiernos, el Señor los mantuvo lejos del temor de los hombres.

En este tiempo cayó sobre mí otra gran prueba de espíritu,
que me parecía tan extraña y sorprendente,
que no podía creer que el Señor me pidiera tal servicio,
pues yo era muy débil y despreciable, muy incompetente y llena de dudas,
mi comprensión poco profunda, y mi capacidad pobre y baja a mis propios ojos.
Mirar tanto mi insuficiencia, me hizo luchar fuertemente contra lo que el Señor me pedía,
clamando muchas veces dentro de mí: "`De seguro esto debe ser algo para engañarme,
porque el Señor no podría pedir tal cosa de mí,
al ver que hay tantos hombres sabios y buenos que son más
honorables y adecuados para el servicio que yo.
¡Oh, Señor, aleja esto de mí y pídeme algo más, algo que yo pueda realizar mejor!`"

Así razonaba y luchaba contra Él,
hasta que mi pena llegó a ser tan grande que no sabía
si el Señor me volvería a aceptar alguna vez.
Entonces clamaba al Señor una y otra vez diciendo: "`¡Señor, si Tú me has hallado digna,
haz mi camino sencillo delante de mí y yo te seguiré,
porque Tú sabes que no te ofendería voluntariamente!`"
Pero sabiendo que soy de capacidad débil,
no pensé que el Señor escogería un instrumento tan despreciable como yo,
ni desearía que yo dejara mi lugar de habitación,
ni a mis tiernos hijos (que eran pequeños), para ir al Rey Carlos II,
a cien millas de distancia,
y entregar un testimonio tan directo como el que el Señor había pedido.

Esto me hizo andar cabizbaja bajo esta prueba por muchos meses,
y a menudo luchaba contra ella.
Pero no podía descansar,
a menos que me rindiera para obedecer al Señor en todas las cosas que Él me pedía,
y aunque me parecía difícil y extraño,
el Señor hizo que las cosas difíciles fueran fáciles, según Su promesa.
Cuando me alejé de mis hijos,
sólo sabía que mi vida podría ser demandada por mi testimonio,
pero la voluntad del Señor aparecía muy clara; no obstante, mientras miraba a mis hijos,
mi corazón los anhelaba.
Entonces estas palabras brotaron dentro de mí: "`Si puedes creer,
verás todas las cosas cumplidas y regresarás en paz, y tu recompensa estará contigo.`"
Bendito sea por siempre el nombre y poder del Señor,
porque Él me sustentó en mi travesía, me dio fuerza para hacer Su voluntad,
y me brindó Su presencia viva para acompañarme;
lo cual es el consuelo más grande que se pueda disfrutar.

[.offset]
Este fue mi testimonio al Rey Carlos II, en el mes once de 1670.

[.embedded-content-document.testimony]
--

"`Esto es para ti, oh, rey:
Oye lo que el Señor ha encomendado a mi cargo con respecto a ti.
Así como has sido la razón de mucha aflicción,
así te afligirá el Señor. Yo entraré en juicio contra los que han sido la causa
de persecución y del derramamiento de la sangre de Mis amados hijos,
el día que Yo los llame a cuentas, dice el Señor. Por tanto,
oye y teme al Señor Dios del cielo y de la tierra,
porque de Sus juicios justos todos serán hechos partícipes;
desde el rey que se siente en el trono,
hasta el mendigo que se sienta en el estercolero.`"

--

Yo entregué este testimonio en sus manos, con estas palabras: "`Oye, oh rey,
y teme al Señor Dios del cielo y la tierra.`"
Realmente puedo decir,
que el pavor del Altísimo Dios que estaba sobre mí me hacía temblar,
y que había gran agonía sobre mi espíritu, a tal punto,
que el rostro del rey palideció y con voz triste dijo: "`Te lo agradezco, buena mujer.`"
¡Mi alma honra y magnifica el nombre y poder del Señor mi Dios,
por mantenerme fiel a Su testimonio y darme la fuerza de hacer Su voluntad,
pues Él ciertamente cumplió Su promesa: "`Si crees,
regresarás en paz y mi recompensa estará contigo.`"
Así bendijo el Señor mi salida.
Su presencia estuvo conmigo en mi travesía, Él preservó a mi familia bien,
y mi regreso a casa fue con gozo y paz en mi corazón. ¡Eternas alabanzas,
gloria y honor sean dadas Al que se sienta en el trono y al Cordero, para siempre!

Recuerden la bondad del Señor para con Sus hijos,
aquellos que fielmente lo siguen y obedecen con todo su corazón,
aunque lo hagan con muchas debilidades.
Yo le di paso al razonador muchas veces,
hasta que mi pena llegó a ser tan grande que no sabía qué camino tomar.
De hecho, eso oscureció mi vista, hirió mi vida y sumió mi alma en dificultad.
Pero le plació al Señor aparecer en la hora de necesidad
y hacer retroceder al enemigo de la paz de mi alma.
Él me ha mostrado que Él escoge al débil,
a los que son nada ante sus propios ojos y no pueden hacer nada;
ni siquiera pronunciar una palabra sino la que Él les ha dado.
Así son cumplidas las Escrituras de verdad en nuestro día,
como también lo fueron en el pasado, que '`ninguna carne se gloríe en Su presencia.`'

Poco tiempo después,
vinieron oficiales y demandaron dinero para el rey
debido a nuestra reunión. Mi esposo les respondió:
"`Si yo le debiera dinero al rey, de seguro se lo pagaría,
pero viendo que no le debo dinero, no le pagaré nada.`"
Ellos le pidieron permiso para confiscar sus bienes, a lo que él les respondió:
"`Si ustedes confiscan mis bienes, yo no puedo estorbarlos,
pero no les daré permiso para que lo hagan;
ni tampoco seré cómplice de su confiscación.`" Los oficiales vieron nuestra inocencia,
porque nosotros estábamos en nuestra tienda, en nuestra vocación,
con las manos en nuestra labor y nuestros hijos con nosotros.
Entonces el alguacil (cuyo nombre era Juan) inclinó su cabeza sobre su mano,
y con pesar dijo: "`Está contra mi consciencia quitarles los bienes.`"
Entonces dije: "`Juan, ten cuidado de hacerle daño a tu consciencia,
porque ¿qué más puede hacer el Señor por ti que colocar Su buen Espíritu en tu corazón,
para que te enseñe qué debes hacer y qué debes dejar de hacer?`"
Él dijo: "`No sé qué hacer en este asunto.
Si pagar el dinero una vez fuera suficiente, yo mismo lo haría,
pero esto nunca terminará. Continuará así mientras se mantengan yendo a las reuniones,
porque los gobernantes han hecho tales leyes,
que nunca se ha visto algo así en ninguna época.`"
Yo dije: "`Juan,
cuando le has hecho daño a tu consciencia y has traído una carga sobre tu espíritu,
los gobernantes no pueden quitar eso de ti.
Si vas a los gobernantes y les dices:
'`He hecho lo que estaba contra mi consciencia hacer,`' ellos pueden
decirte lo que los gobernantes le dijeron a Judas:
'`¿Qué nos importa a nosotros?
¡Allá tú!`'`"

Los oficiales que estaban con él vinieron y derribaron nuestros bienes,
pero el poder del Señor los golpeó, al punto que sus rostros empalidecieron,
sus labios temblaban y sus manos se sacudían tanto,
que no podían sostener nuestras cosas por mucho tiempo.
Entonces, le encargaron a un pobre hombre que los cogiera, pero él se rehusó,
hasta que lo forzaron y pusieron nuestras cosas sobre sus brazos y hombros.
Pero él, con el aspecto como de un hombre muerto, replicó:
"`¡Ustedes me fuerzan a hacer lo que no pueden hacer por sí mismos,
yo tampoco puedo!`" Él temblaba mucho,
aunque nosotros no habíamos dicho nada después de que entraron,
más bien nos regocijaba que el Señor nos hallara
dignos de sufrir por Su bendita verdad y testimonio.

Poco tiempo después,
hubo una reunión para tasar los bienes que nos quitaron a nosotros y a otros Amigos.
Se reunieron muchos en una casa: Siete hombres llamados jueces, oficiales y alguaciles,
un administrador y muchos más de sus socios; una gran habitación llena de ellos.
Yo estaba trabajando en nuestra tienda,
y al ver al oficial que se llevaba algunos de los bienes para ser tasados,
de inmediato entró en mi corazón ir tras él. Yo no sabía qué debía decirles,
lo cual me hizo considerar un poco por qué debía ir,
pero poco a poco descansó sobre mí ir.

Cuando entré por la puerta, me senté como una tonta por media o tres cuartos de hora,
sin una palabra que decir.
Pero cuando entré, ellos se inquietaron mucho en sus mentes y se apuraron en sus asuntos.
Dijeron: "`No podemos hacer nada mientras ella esté con nosotros.`"
Los jueces se pedían unos a otros, varias veces, que me mandaran a quitar diciendo:
"`No haremos ningún negocio hoy,
pasaremos nuestro tiempo en vano si esta mujer se sienta aquí.`"
En varias ocasiones me tentaron a decir lo que tenía que decir,
y que luego me fuera,
pero no pudieron prevalecer contra mí. Entonces llamaron
al hombre de la casa para que me quitara,
declarándole solemnemente que nunca volverían a su casa a menos que él me quitara.
Pero el hombre no tenía poder para tocarme, y al estar muy angustiado dijo: "`Señor,
no puedo ponerle las manos encima, ella es mi vecina honesta.`"
Entonces se volvió hacia mí y me dijo: "`Por favor vecina Stirredge,
si tiene algo que decir, dígalo, para que pueda irse.`"
Uno de los jueces con gran rabia y furia solemnemente protestó diciendo,
que nunca más se sentaría con ellos si no me quitaban,
y se maravilló de la locura de ellos por dejarme en paz.
Luego abrió la puerta trasera y salió, como si quisiera irse,
pero al poco tiempo volvió a entrar y dijo: "`¡Qué,
¿sigue ella aquí? Me sorprende la locura de ustedes!`"

Por fin,
el poder del Señor vino sobre mí y llenó mi corazón de una advertencia para ellos.
Yo les dije: "`Es en vano que luchen contra el Señor y Su pueblo.
La obra de ustedes no prosperará,
pues descubrirán que el gran Dios del cielo y la tierra es demasiado fuerte para ustedes.
Los exhorto a que se arrepientan y corrijan sus vidas, antes de que sea demasiado tarde,
porque el Señor los herirá sin que se den cuenta y a una hora inesperada.
Por tanto, recuerden que el Señor les ha concedido un día de advertencia,
antes de que la destrucción venga sobre ustedes.`"
Esto y mucho más fluyó a través mío en ese momento,
y le plació al Señor en un tiempo muy corto, cumplir este testimonio sobre ellos.
Porque en unas pocas semanas, mientras ellos se alegraban en una fiesta,
dos de ellos murieron de repente después de la cena,
y el resto apenas escapó. Esto sucedió alrededor del año 1674.

Escribo esto no para regocijarme de la caída de nuestros enemigos,
sino para que consideren la bondad,
misericordia y tratos del Señor con Su pueblo en todas las épocas,
y para que recuerden Su misericordia y paciencia hacia los malvados;
los que Lo provocan a derramar Su venganza sobre sus cabezas.
Sin embargo, cuán grande es Su misericordia,
pues Él siempre advierte a los malos y les da tiempo
para que se arrepientan y corrijan sus vidas,
para que Él pueda ser claro el día de rendir cuentas,
el cual ciertamente vendrá sobre todos.

Por tanto, mis queridos hijos, recuerden su fin y el día de rendir cuentas,
y mantengan refrenadas sus lenguas, porque el que no experimenta un freno en su lengua,
la religión del tal es vana.
Si van a ser herederos del reino de los cielos y de la corona inmortal,
deben tomar la cruz cada día, porque "`No Cruz, No Corona`"^
footnote:[__No Cruz, No Corona,__ es el título del famoso libro de William Penn,
escrito durante su encarcelamiento en la Torre de Londres,
en 1669.]. La cruz mantendrá sus mentes en sujeción al Dios vivo, y al estar en sujeción,
y temblar y no pecar,
los mantendrá cerca del Señor en un conocimiento vivo de
Él. Entonces Él se deleitará en bendecirlos más y más,
instruirlos y aconsejarlos en Su camino, el cual es puro y santo,
y no admitirá ninguna impiedad ni impureza.

Tengan cuidado del mundo y su gente.
No se familiaricen demasiado con ellos,
ni dejen que sus espíritus se mezclen con los de ustedes,
porque esto ha sido la ruina de muchos que han tenido
un buen comienzo y que han viajado en el camino,
pero han errado por falta de vigilancia y por no aferrarse al Guía de
su juventud--la luz de Cristo Jesús. Este es el camino de salvación,
y el que anda por otro camino es un ladrón y salteador.
Ustedes conocen el camino,
ustedes han sido formados en él. La preocupación de mi espíritu ahora,
es que sigan en él, y que se preocupen por sus hijos,
como su padre y yo nos hemos preocupado por ustedes.
Fórmenlos en el camino de la verdad y manténgalos
fuera de los pobres rudimentos de este mundo,
para que crezcan en la sencillez y mantengan el lenguaje sencillo
(el cual se ha convertido en algo muy irrelevante hoy,
entre muchos profesantes de la verdad).
Yo realmente no estaba limpia a la vista de Dios (mi camino
estaba cubierto de espinas y no podía avanzar),
hasta que le rendía obediencia a Él en las cosas
pequeñas. Entonces salía a caminar a solas,
en privado, como solía hacer cuando las cosas me pesaban.
¡Oh, aquel desolado lugar donde solía retirarme,
cuántas veces se ha encontrado mi alma con mi Amado ahí,
quien dulcemente me ha consolado cuando mi alma estaba enferma
de amor y llena de dudas por temor a que Él me hubiera abandonado!
Pero bendito sea Su nombre que vive para siempre,
porque Él aparecía en el momento de necesidad, cuando mi alma estaba angustiada por Él;
entonces era cuando yo llegaba a apreciarlo verdaderamente.
Sí, esta es la manera en que el Señor trata con Su pueblo,
para enseñarles a ser humildes y capacitarlos como hijos,
a fin de que aprendan obediencia en todas las cosas para hacer Su voluntad.
Este es Su objetivo al disciplinar; hacer que Sus hijos sean aptos para Su servicio.

Yo poco pensé en que el Señor me había dado muchos años,
para llevar un testimonio fiel de Su bendita verdad y de la poderosa aparición
y manifestación de Su gloriosa luz y vida a muchos miles que se sentaban en oscuridad.
¡Oh, estos estaban en un estado miserable,
muchas veces más allá de la esperanza de ver un buen día, con horror,
pavor y angustia en sus corazones!
Pero fueron estos los que recibieron y apreciaron la bendita
oferta del amor eterno y gloriosa aparición de Dios,
aunque fue dada en el camino de Sus juicios.
Puedo verdaderamente decir, que mi corazón y mi alma se han deleitado en el juicio,
aunque hayan sido derramadas una angustia tras otra.
Sin embargo,
bendito sea el día que la verdad eterna fue anunciada por primera vez a mis oídos,
cuando tenía diecinueve años. ¡Qué ese día nunca sea olvidado por mí,
es el deseo de mi alma!
Pero más bendito sea el nombre del Señor nuestro Dios, y el brazo derecho de Su poder,
que ha sido manifestado día tras día, y año tras año,
para la continuación de Su obra y preservación de Sus hijos.

[.asterism]
'''

__Elizabeth Stirredge nunca fue ministra en la Sociedad de Amigos,
pero todos la conocían como una que "`había estado en el consejo del Señor,
y vio y oyó Su palabra`" (Jeremías 23:18; LBLA).
Ella fue fiel en lo poco, y el Señor le confió mucho,
dándole gracia y sabiduría para fortalecer a muchos
compañeros de viaje en el camino angosto.
A lo largo de su vida se mantuvo baja y pequeña delante de Su todopoderoso Maestro,
inclinándose ante Su más pequeña aparición y aferrándose a Su cruz.
Por tanto, al ser pequeña a sus propios ojos,
el Señor era libre de exaltarla y usarla para Su propia gloria y propósito,
lo cual hizo con frecuencia,
a menudo de maneras muy notables (ver el resto de su diario).__

__Como muchos otros que se aferraron a la Verdad en aquel día,
Elizabeth Stirredge experimentó su parte en las persecuciones y encarcelamientos,
y a veces "`alegremente aceptó el saqueo de sus bienes.`"
Increíblemente,
acogió tales pruebas
como señales del amor de Dios hacia ella,
diciendo a menudo que no tenía mayor alegría que
ser contada digna de sufrir por Su nombre.__
